spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.154.52:3306/videodb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  http:
    encoding:
      force: true

server:
  port: 8080
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      example:
        movies:
          mapper:
            debug
